name: Jupyter check

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Ensure Clean Jupyter Notebooks
      uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
